bpm location master with APIs is implemented
khanshadab09/RE-Billing pull request #6
Opened 2023-07-21 11:32 UTC by gauravgothi

location master have status 0 instead of active /inactive by default.
I have given default value is 0
Please check

2023-07-21 12:29 UTC, khanshadab09 requested changes

2023-07-21 12:29 UTC, khanshadab09 commented on src/main/java/in/co/mpwin/rebilling/controller/LocationController.java
> +            List<LocationMaster> regionList = locationService.findAllByStatus(status);
use, GetDistinctRegion instead of findAllByStatus...

2023-07-21 12:29 UTC, khanshadab09 commented on src/main/java/in/co/mpwin/rebilling/services/LocationService.java
> +
method of distinct Region is missing in the service

2023-07-22 05:40 UTC, gauravgothi commented on src/main/java/in/co/mpwin/rebilling/controller/LocationController.java
> +            List<LocationMaster> regionList = locationService.findAllByStatus(status);
It is changed now

2023-07-22 05:40 UTC, gauravgothi commented on src/main/java/in/co/mpwin/rebilling/services/LocationService.java
> +
It is also added please check

2023-07-27 08:43 UTC, khanshadab09 approved these changes

2023-07-27 08:44 UTC, merged

2023-07-27 08:44 UTC, khanshadab09 commented
Done